"""empty message

Revision ID: 286920f27710
Revises: 2a3a799732da
Create Date: 2020-06-28 19:21:31.392558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286920f27710'
down_revision = '2a3a799732da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Eat', sa.Column('orders_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Eat', 'orders', ['orders_id'], ['id'])
    op.drop_column('Eat', 'list_or')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eat', sa.Column('list_or', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Eat', type_='foreignkey')
    op.drop_column('Eat', 'orders_id')
    op.drop_table('orders')
    # ### end Alembic commands ###
