"""empty message

Revision ID: 2a3a799732da
Revises: 7926bc314355
Create Date: 2020-06-28 19:04:06.973307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3a799732da'
down_revision = '7926bc314355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('List_order')
    op.add_column('Eat', sa.Column('orders_id', sa.Integer(), nullable=True))
    op.drop_constraint('Eat_list_or_fkey', 'Eat', type_='foreignkey')
    op.create_foreign_key(None, 'Eat', 'orders', ['orders_id'], ['id'])
    op.drop_column('Eat', 'list_or')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eat', sa.Column('list_or', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Eat', type_='foreignkey')
    op.create_foreign_key('Eat_list_or_fkey', 'Eat', 'List_order', ['list_or'], ['id'])
    op.drop_column('Eat', 'orders_id')
    op.create_table('List_order',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"List_order_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='List_order_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='List_order_pkey')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
