"""empty message

Revision ID: 4931bf99c113
Revises: 286920f27710
Create Date: 2020-06-28 20:14:49.842434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4931bf99c113'
down_revision = '286920f27710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('items_order', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    op.drop_constraint('Eat_orders_id_fkey', 'Eat', type_='foreignkey')
    op.drop_column('Eat', 'orders_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eat', sa.Column('orders_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Eat_orders_id_fkey', 'Eat', 'orders', ['orders_id'], ['id'])
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    op.drop_table('Orders')
    # ### end Alembic commands ###
