"""empty message

Revision ID: 534a82bbfd38
Revises: 9d5396147be4
Create Date: 2020-06-28 21:42:59.296398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534a82bbfd38'
down_revision = '9d5396147be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'status')
    # ### end Alembic commands ###
