"""empty message

Revision ID: 63e810b865d8
Revises: a0d0dc45f85d
Create Date: 2020-06-23 20:30:26.769454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e810b865d8'
down_revision = 'a0d0dc45f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_eat',
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('eat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['Basket.id'], ),
    sa.ForeignKeyConstraint(['eat_id'], ['Eat.id'], )
    )
    op.drop_column('Eat', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eat', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_table('basket_eat')
    op.drop_table('Basket')
    # ### end Alembic commands ###
