"""empty message

Revision ID: 872dc9a139d3
Revises: 8e6eddde08c4
Create Date: 2020-06-27 21:58:15.647028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872dc9a139d3'
down_revision = '8e6eddde08c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('List_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Eat', sa.Column('list_or', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Eat', 'List_order', ['list_or'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Eat', type_='foreignkey')
    op.drop_column('Eat', 'list_or')
    op.drop_table('List_order')
    # ### end Alembic commands ###
