"""empty message

Revision ID: 8e6eddde08c4
Revises: e5f0ffb56b0c
Create Date: 2020-06-23 21:40:52.163998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6eddde08c4'
down_revision = 'e5f0ffb56b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eat', sa.Column('basket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Eat', 'Basket', ['basket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Eat', type_='foreignkey')
    op.drop_column('Eat', 'basket_id')
    # ### end Alembic commands ###
