"""empty message

Revision ID: 9d5396147be4
Revises: 4931bf99c113
Create Date: 2020-06-28 20:19:58.613124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5396147be4'
down_revision = '4931bf99c113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('items_order', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Eat', 'orders_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eat', sa.Column('orders_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('Orders')
    # ### end Alembic commands ###
