"""empty message

Revision ID: a0d0dc45f85d
Revises: e8f955c31872
Create Date: 2020-05-27 23:30:48.371141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d0dc45f85d'
down_revision = 'e8f955c31872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('hesh', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'hesh')
    # ### end Alembic commands ###
