"""empty message

Revision ID: b8a367194e5f
Revises: 947823191c8d
Create Date: 2020-07-10 15:10:51.176577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8a367194e5f'
down_revision = '947823191c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders_User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders_User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Orders_User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('items_order', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Orders_User_pkey')
    )
    # ### end Alembic commands ###
