"""empty message

Revision ID: e209eeb3a8cb
Revises: eebda5909122
Create Date: 2020-07-09 16:21:47.874023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e209eeb3a8cb'
down_revision = 'eebda5909122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('News_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('News_page')
    # ### end Alembic commands ###
