"""empty message

Revision ID: e8f955c31872
Revises: 9b17c8ada40a
Create Date: 2020-05-27 17:43:03.866027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f955c31872'
down_revision = '9b17c8ada40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_name_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_name_key', 'User', ['name'])
    # ### end Alembic commands ###
